GET http://localhost:8000/api/users

###

POST http://localhost:8000/api/users Content-Type: application/json

{
"firstName": "Kyle",
"lastName": "Lee",
"email":"test@gmail.com",
"password": "password"
}